#!/bin/bash

#welcome Message
echo "Welcome to the Directory Storage Utilization Report Tool."
sleep 1
echo "Version 1.0"
sleep 1
echo "created by Stephanie"
sleep 1
echo "-----------------start Report Generation------------------"
sleep 1

#Define Report and file Details
read -p "Enter the directory that you'd like to generate the repo
rtfor: "dirReport
sleep 1
read -p "Enter the absolute path where you'd like to save the report: " absoPath
sleep 1
read -p "Enter the desired file name for the reoprt: " reportFile
sleep 1

#Define teh full path and File Name for Final Report
finalReport=$absoPath/$reportFile.txt

#Generate the Report
echo "------------Report Header-------------"
echo "This report was generated by $(whoami)" >> $finalReport
echo "This report was generate on $(date)" >> $finalReport
echo "---------------Report Details-------------" >> $finalReport
sudo du -sh $dirReport >> $finalReport

if [ $? = 0 ]; then
       echo "Report genration was successful. Your report is located here: $finalReport"; echo "--------------------Report Complete--------------" $finalReport
else
       echo "An error occured during file generation. Try again."

fi       
